apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: democratic-csi-ssh-key
  namespace: storage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: democratic-csi-ssh-key
    creationPolicy: Owner
    template:
      data:
        ssh-privatekey: "{{ .opensshkey | b64dec }}"
  data:
    - secretKey: opensshkey
      remoteRef:
        key: Robin NAS democratic-csi
        property: openssh-private-key-b64
