apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshotClass
metadata:
  name: zfs-nfs
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "false"
driver: nfs.democratic-csi.robin
deletionPolicy: Delete
parameters:
  detachedSnapshots: "true"
