apiVersion: netbird.io/v1alpha1
kind: NetworkRouter
metadata:
  name: stasky
  namespace: netbird
spec:
  dnsZoneRef:
    name: cluster.stasky.win
  workloadOverride:
    podTemplate:
      spec:
        containers:
          - name: netbird
            env:
              - name: NB_DISABLE_UPDATE_SETTINGS
                value: "false"
