apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbird-credentials
  namespace: network
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: netbird-credentials
    creationPolicy: Owner
  data:
    - secretKey: NB_SETUP_KEY
      remoteRef:
        key: NetBird
        property: setup_key_cluster
