apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: victus
  namespace: flux-system
spec:
  targetNamespace: food
  commonMetadata:
    labels:
      app.kubernetes.io/name: victus
  dependsOn:
    - name: app-template
    - name: external-secrets-clustersecretstore
    - name: rook-ceph-cluster
    - name: pocket-id
  path: ./kubernetes/apps/food/victus/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: victus
      namespace: food
    - apiVersion: external-secrets.io/v1
      kind: ExternalSecret
      name: victus-secret
      namespace: food
