apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: newt-credentials
  namespace: network
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: newt-credentials
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: newt-config
