apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: newt-credentials
  namespace: network
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: newt-credentials
    creationPolicy: Owner
  data:
    - secretKey: NEWT_ID
      remoteRef:
        key: Newt
    - secretKey: NEWT_SECRET
      remoteRef:
        key: Newt
