apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-template
  namespace: flux-system
spec:
  targetNamespace: flux-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: app-template
  path: ./kubernetes/apps/flux-system/sources/app-template
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  healthChecks:
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: OCIRepository
      name: app-template
      namespace: flux-system
