apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netbird-api-key
  namespace: netbird
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: netbird-mgmt-api-key
    creationPolicy: Owner
  data:
    - secretKey: NB_API_KEY
      remoteRef:
        key: NetBird
        property: api_token
