apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: stasky-http-to-https
  namespace: network
spec:
  parentRefs:
    - name: stasky
      sectionName: http
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
