apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sabnzbd-vpn-secret
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: sabnzbd-vpn-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: mullvad-sabnzbd-config
