apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gotify-secret
  namespace: notifications
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: gotify-secret
    creationPolicy: Owner
  data:
    - secretKey: GOTIFY_OIDC_CLIENTID
      remoteRef:
        key: Gotify
        property: client_id
    - secretKey: GOTIFY_OIDC_CLIENTSECRET
      remoteRef:
        key: Gotify
        property: client_secret
    - secretKey: GOTIFY_DEFAULTUSER_PASS
      remoteRef:
        key: Gotify
        property: admin_password
