apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qbittorrent-vpn-secret
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: qbittorrent-vpn-secret
    creationPolicy: Owner
  data:
    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: Mullvad - qBittorrent
        property: private-key
    - secretKey: WIREGUARD_ADDRESSES
      remoteRef:
        key: Mullvad - qBittorrent
        property: address
