# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radarr-anime
  namespace: media
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      radarr-anime:
        strategy: Recreate
        containers:
          app:
            image:
              repository: ghcr.io/linuxserver/radarr
              tag: "6.3.0.10514-ls313"
            env:
              PUID: "1000"
              PGID: "1000"
              UMASK: "002"
              TZ: Europe/Andorra
              DOCKER_MODS: linuxserver/mods:universal-package-install
              INSTALL_PACKAGES: mkvtoolnix|python3
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 20m
                memory: 256Mi
              limits:
                memory: 1Gi

    defaultPodOptions:
      annotations:
        reloader.stakater.com/auto: "true"
      automountServiceAccountToken: false

    service:
      app:
        controller: radarr-anime
        ports:
          http:
            port: 7878

    route:
      app:
        hostnames:
          - radarr-anime.stasky.win
        parentRefs:
          - name: stasky
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app

    persistence:
      anime-tracks:
        type: configMap
        name: anime-tracks
        defaultMode: 0555
        globalMounts:
          - path: /config/scripts
      config:
        accessMode: ReadWriteOnce
        size: 2Gi
        storageClass: ceph-block
        retain: true
        globalMounts:
          - path: /config
      media:
        existingClaim: media-data
        globalMounts:
          - path: /data
