apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
spec:
  targetNamespace: network
  commonMetadata:
    labels:
      app.kubernetes.io/name: external-dns
  dependsOn:
    - name: external-secrets-clustersecretstore
  path: ./kubernetes/apps/network/external-dns/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: external-dns
      namespace: network
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: HelmRepository
      name: external-dns
      namespace: network
    - apiVersion: external-secrets.io/v1
      kind: ExternalSecret
      name: external-dns-cloudflare
      namespace: network
