apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gbi-secret
  namespace: documents
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: gbi-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: GoBillIt
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gbi-config
  namespace: documents
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: gbi-config
    creationPolicy: Owner
  data:
    - secretKey: config.yaml
      remoteRef:
        key: GoBillIt - config.yaml
        property: config.yaml
