apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: toolhive-secret
  namespace: ai
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: toolhive-secret
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: toolhive-config
