---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app flux-webhooks
  namespace: flux-system
spec:
  targetNamespace: flux-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: external-secrets-clustersecretstore
    - name: external-dns
  path: ./kubernetes/apps/flux-system/webhooks/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  healthChecks:
    - apiVersion: external-secrets.io/v1
      kind: ExternalSecret
      name: github-webhook-secret
      namespace: flux-system
    - apiVersion: notification.toolkit.fluxcd.io/v1
      kind: Receiver
      name: github-receiver
      namespace: flux-system
    - apiVersion: externaldns.k8s.io/v1alpha1
      kind: DNSEndpoint
      name: flux-webhook
      namespace: flux-system
