apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: victus-secret
  namespace: food
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: victus-secret
    creationPolicy: Owner
  data:
    - secretKey: SESSION_SECRET
      remoteRef:
        key: Victus
        property: session_secret
    - secretKey: OIDC_CLIENT_ID
      remoteRef:
        key: Victus
        property: client_id
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: Victus
        property: client_secret
    - secretKey: MEALIE_API_KEY
      remoteRef:
        key: Victus
        property: mealie_api_key
