apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qui-oidc
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: qui-oidc
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: qui-config
