apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qui-oidc
  namespace: media
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: qui-oidc
    creationPolicy: Owner
  data:
    - secretKey: QUI__OIDC_CLIENT_ID
      remoteRef:
        key: qui
        property: client_id
    - secretKey: QUI__OIDC_CLIENT_SECRET
      remoteRef:
        key: qui
        property: client_secret
