apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  targetNamespace: cert-manager
  commonMetadata:
    labels:
      app.kubernetes.io/name: cert-manager
  path: ./kubernetes/apps/cert-manager/cert-manager/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  timeout: 5m
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: cert-manager
      namespace: cert-manager
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: OCIRepository
      name: cert-manager
      namespace: cert-manager
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-secrets
  namespace: flux-system
spec:
  commonMetadata:
    labels:
      app.kubernetes.io/name: cert-manager
  dependsOn:
    - name: external-secrets-clustersecretstore
  path: ./kubernetes/apps/cert-manager/cert-manager/secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  healthChecks:
    - apiVersion: external-secrets.io/v1
      kind: ExternalSecret
      name: cluster-settings
      namespace: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-config
  namespace: flux-system
spec:
  targetNamespace: cert-manager
  commonMetadata:
    labels:
      app.kubernetes.io/name: cert-manager
  dependsOn:
    - name: cert-manager
    - name: cert-manager-secrets
  retryInterval: 1m
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-settings
  path: ./kubernetes/apps/cert-manager/cert-manager/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  timeout: 5m
  healthChecks:
    - apiVersion: external-secrets.io/v1
      kind: ExternalSecret
      name: cloudflare-api-token
      namespace: cert-manager
    - apiVersion: external-secrets.io/v1
      kind: ExternalSecret
      name: ribera-cat-dns-token
      namespace: cert-manager
