apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ribera-cat-dns-token
  namespace: cert-manager
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: ribera-cat-dns-token
    creationPolicy: Owner
  data:
    - secretKey: api-token
      remoteRef:
        key: CF - ribera.cat Edit Zone DNS
        property: credential
