apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: database
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: cloudnative-pg
    namespace: database
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    crds:
      create: true
    resources:
      requests:
        cpu: 20m
        memory: 128Mi
      limits:
        memory: 512Mi
