apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: redis-operator
  namespace: database
spec:
  interval: 1h
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  url: oci://ghcr.io/ot-container-kit/charts/redis-operator
  ref:
    tag: "0.25.0"
