apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-immich-user
  namespace: database
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: postgres-immich-user
    creationPolicy: Owner
    # CNPG requires basic-auth for managed role passwords.
    template:
      type: kubernetes.io/basic-auth
      data:
        username: immich
        password: "{{ .db_password }}"
  data:
    - secretKey: db_password
      remoteRef:
        key: Immich
        property: db_password
