apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: external-dns-cloudflare
  namespace: network
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: external-dns-cloudflare
    creationPolicy: Owner
  data:
    - secretKey: cloudflare-api-token
      remoteRef:
        key: CF - stasky.win Edit Zone DNS
        property: credential
