apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: network
spec:
  interval: 1h
  chart:
    spec:
      chart: external-dns
      version: "1.21.1"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: network
  values:
    podAnnotations:
      reloader.stakater.com/auto: "true"

    provider:
      name: cloudflare

    sources:
      - crd

    domainFilters:
      - stasky.win

    policy: sync
    txtOwnerId: homeops-external-dns

    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: external-dns-cloudflare
            key: cloudflare-api-token

    serviceAccount:
      create: true

    rbac:
      create: true

    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        memory: 64Mi
