apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: immich
  namespace: flux-system
spec:
  targetNamespace: photos
  commonMetadata:
    labels:
      app.kubernetes.io/name: immich
  dependsOn:
    - name: external-secrets-clustersecretstore
    - name: postgres
    - name: redis
    - name: rook-ceph-cluster
    - name: intel-gpu-plugin
  path: ./kubernetes/apps/photos/immich/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  interval: 30m
  retryInterval: 1m
  timeout: 15m
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: immich
      namespace: photos
    - apiVersion: source.toolkit.fluxcd.io/v1
      kind: OCIRepository
      name: immich
      namespace: photos
    - apiVersion: external-secrets.io/v1
      kind: ExternalSecret
      name: immich-secret
      namespace: photos
